<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Oswaldo Felix">

  
  
  
    
  
  <meta name="description" content="This report analyzes differences in the abundance and size of California Spiny Lobsters (Panulirus interruptus) observed at five locations along the Santa Barbara coastline by the Santa Barbara Coastal Long Term Ecological Research program (SBC LTER).">

  
  <link rel="alternate" hreflang="en-us" href="/project/lobsters/kat_waldo_esm206_ass4_lobsters/">

  


  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      
        
      

      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/project/lobsters/kat_waldo_esm206_ass4_lobsters/">

  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@ozziedudias">
  <meta property="twitter:creator" content="@ozziedudias">
  
  <meta property="og:site_name" content="Waldo&#39;s World">
  <meta property="og:url" content="/project/lobsters/kat_waldo_esm206_ass4_lobsters/">
  <meta property="og:title" content="Spiny lobster abundance and size within Santa Barbara LTER | Waldo&#39;s World">
  <meta property="og:description" content="This report analyzes differences in the abundance and size of California Spiny Lobsters (Panulirus interruptus) observed at five locations along the Santa Barbara coastline by the Santa Barbara Coastal Long Term Ecological Research program (SBC LTER)."><meta property="og:image" content="img/map[gravatar:%!s(bool=false) shape:circle]">
  <meta property="twitter:image" content="img/map[gravatar:%!s(bool=false) shape:circle]"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-11-15T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2019-11-15T00:00:00&#43;00:00">
  

  


    









<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/project/lobsters/kat_waldo_esm206_ass4_lobsters/"
  },
  "headline": "Spiny lobster abundance and size within Santa Barbara LTER",
  
  "datePublished": "2019-11-15T00:00:00Z",
  "dateModified": "2019-11-15T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Oswaldo Felix"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Waldo's World",
    "logo": {
      "@type": "ImageObject",
      "url": "/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "This report analyzes differences in the abundance and size of California Spiny Lobsters (Panulirus interruptus) observed at five locations along the Santa Barbara coastline by the Santa Barbara Coastal Long Term Ecological Research program (SBC LTER)."
}
</script>

  

  


  


  





  <title>Spiny lobster abundance and size within Santa Barbara LTER | Waldo&#39;s World</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Waldo&#39;s World</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Waldo&#39;s World</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/files/cv.pdf"><span>CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item">
        <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article article-project">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Spiny lobster abundance and size within Santa Barbara LTER</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    Nov 15, 2019
  </span>
  

  

  

  
  
  

  
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<p><img src="https://cimioutdoored.org/ca-spiny-lobster/california-spiny-lobster/" /></p>
<p>This report analyzes differences in the abundance and size of California Spiny Lobsters (Panulirus interruptus) observed at five locations along the Santa Barbara coastline by the Santa Barbara Coastal Long Term Ecological Research program (SBC LTER). Spiny lobsters play a critical predatory role in Southern California’s giant kelp forests, but are threatened by fishing pressure. The California Fish and Game’s Network of Marine Protected Areas (MPAs), Naples and Isla Vista, provide a refuge from fishing pressure and thus a unique oportunity to compare and contrast lobsters living in communities subject to and sheltered from fishing. To this end, this report examines:
- A: changes in annual lobster abundance (counts) over time by site;
- B: shifts in lobster size distributions between 2012 and 2018; and
- C: differences between mean lobster sizes at MPA vs. non-MPA sites in 2012 and 2018.</p>
<p>As a result of this examination, it was found that:
- between MPA and non-MPA sites, there was a significant difference (p-value = 0.003) in lobster size in 2012, and a significant difference (p-value = 0.000003) in lobster size in 2018;
- within MPA sites, there was a significant (p-value = 0.0004) mean size difference between lobsters observed in 2012 and 2018; and
- within non-MPA sites, there was not a significant (p-value = 0.204) mean size difference in lobsters observed between 2012 and 2018.</p>
<p>These findings provide insight into kelp forest management, indicating that MPAs could be effective at helping support healthy lobster populations.</p>
<p>DATA AND METHODS:
The data used in this report, from the SBC LTER’s two study reefs located in or near the Naples and Isla Vista MPAs, ranges from 2012 to present (2019). Observations were collected annually by divers in late summer before the start of the fishing season from two sites located within the MPAs and three located outside of the MPAs (Arroyo Quemado, Mohawk and Carpinteria). The dependent variables examined were time (the year of observation), and locaton (the site), and the independent variables examined were size (the carapace length in millimeters ) and count (the number of lobsters). Statistical difference was assessed using a two-sided t-test with a Welsh assumption, and a level of significance of 0.05. Analysis was performed using Rstudio software version 1.2.1335.</p>
<pre class="r"><code># ----
# run libraries and read data
# ----

library(tidyverse)
library(janitor)
library(lubridate)
library(kableExtra)

lobster_df &lt;- read_csv(here::here(&quot;csv&quot;, &quot;lobster_abundance_sbc_lter.csv&quot;), 
                       na = &quot;-99999&quot;) %&gt;% 
  clean_names()

tidy_lob &lt;- lobster_df %&gt;% 
  uncount(count)</code></pre>
<div id="results-a" class="section level2">
<h2>Results A:</h2>
<p>Visually explore changes in annual lobster abundance (counts) by site. After grouping observations to find lobster counts for each year, create a finalized data visualization (no modeling/stats needed) showing changes in annual lobster abundance at the five sites over time.</p>
<pre class="r"><code># ----
# Data wrangling
# ----

lob_site_yr &lt;- tidy_lob %&gt;%
  group_by(year) %&gt;% 
  count(site) %&gt;% 
  dplyr::mutate(
    yr = dplyr::case_when(
      year %in% &quot;2012&quot; ~ &quot;&#39;12&quot;,
      year %in% &quot;2013&quot; ~ &quot;&#39;13&quot;,
      year %in% &quot;2014&quot; ~ &quot;&#39;14&quot;,
      year %in% &quot;2015&quot; ~ &quot;&#39;15&quot;,
      year %in% &quot;2016&quot; ~ &quot;&#39;16&quot;,
      year %in% &quot;2017&quot; ~ &quot;&#39;17&quot;,
      year %in% &quot;2018&quot; ~ &quot;&#39;18&quot;,
    )
  )
   

# ----
# Data plotting
# ----
  
ggplot(data = lob_site_yr, aes(x = yr, y = n)) +
  geom_col(aes(fill = site), show.legend = FALSE, 
           color = &quot;black&quot;,  alpha = 0.8) +
  scale_fill_brewer(palette = &quot;Pastel1&quot;) + # Chose this color palette to have color stand out
  scale_y_continuous(expand = c(0,0)) + # Removed bottom space
  labs(x = &quot;Year&quot;, y = &quot;Number of Lobsters&quot;, title = &quot;Number of Lobsters at Each Site from 2012-2018&quot;, fill = &quot;Site&quot;) +
  theme_minimal() +
  facet_wrap(~site, scales = &quot;free_x&quot;) +
  theme(panel.spacing = unit(2, &quot;lines&quot;))</code></pre>
<p><img src="/project/lobsters/Kat_Waldo_ESM206_Ass4_Lobsters_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Fig. 1: Lobster Abundance per site for years 2012-2018. Note that both sites Naples (NAPL) and Isla Vista (IVEE) are MPAs.</p>
</div>
<div id="results-b" class="section level2">
<h2>Results B:</h2>
<p>Visually explore lobster size distribution shifts by comparing lobster sizes in 2012 and 2018. Visually explore the size distributions for lobsters observed at the 5 different sites in 2012, and in 2018 (i.e. you will have a total of 10 size distributions shown: for each of the 5 sites, one for 2012 and one for 2018). Make a finalized graph that clearly and professionally shows community size distributions at each site in the 2 years, allowing the reader to easily interpret distribution shifts.</p>
<pre class="r"><code># ----
# Data wrangling
# ----

lob_size_yr &lt;- tidy_lob %&gt;% 
  select(year, site, size_mm) %&gt;% 
  filter(year == c(2012,2018))

# ----
# Data plotting
# ----

ggplot(lob_size_yr) +
  # Made geom_violin with areas proportional to count
  geom_violin(show.legend = FALSE, scale = &quot;count&quot;,
              aes(x = site, y = size_mm, fill = site)) + 
  scale_fill_brewer(palette = &quot;Pastel1&quot;) +
  facet_wrap(~year) +
  # Removed bottom space and showed full scale
  scale_y_continuous(expand = c(0,0), limits = c(0,200)) + 
  labs(y = &quot;Size [mm]&quot;, x = &quot;Site&quot;, caption = &quot;Area is proportional to count&quot;,
       title = &quot;Lobster size distribution&quot;) +
  theme_minimal()+
  geom_vline(aes(xintercept = 5.6), color = &quot;black&quot;, linetype = 2, lwd=.5)+
  annotate(geom = &quot;text&quot;,
           x = 3,
           y = 35,
           label = &quot;*&quot;,
           color = &quot;black&quot;,
           size = 7)+
  annotate(geom = &quot;text&quot;,
           x = 5,
           y = 35,
           label = &quot;*&quot;,
           color = &quot;black&quot;,
           size = 7)</code></pre>
<p><img src="/project/lobsters/Kat_Waldo_ESM206_Ass4_Lobsters_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Fig. 2: Distribution of lobster sizes for each site for years 2012 and 2018. Note that MPA sites Naples and Isla Vista are indicated with asterisks (*).</p>
</div>
<div id="results-c" class="section level2">
<h2>Results C:</h2>
<p>Compare mean lobster sizes at MPA vs. non-MPA sites in 2012 and 2018. Here, for each year (2012 and 2018) consolidate the size observations into only two groups: MPA and non-MPA lobsters. Then answer the following four questions:</p>
<pre class="r"><code># ----
# Data wrangling
# ----

lob_mpa &lt;- lob_size_yr %&gt;% 
  filter(site %in% c(&quot;IVEE&quot;, &quot;NAPL&quot;)) 
  
lob_nmpa &lt;- lob_size_yr %&gt;% 
  filter(site %in% c(&quot;AQUE&quot;, &quot;CARP&quot;, &quot;MOHK&quot;)) 

# MPA 2012
sample_mpa_12 &lt;- lob_mpa %&gt;%
  filter(year == 2012) %&gt;% 
  pull(size_mm)

# Non-MPA 2012  
sample_nmpa_12 &lt;- lob_nmpa %&gt;%
  filter(year == 2012) %&gt;% 
  pull(size_mm)

# MPA 2018
sample_mpa_18 &lt;- lob_mpa %&gt;% 
  filter(year == 2018) %&gt;% 
  pull(size_mm)

# Non-MPA 2018
sample_nmpa_18 &lt;- lob_nmpa %&gt;% 
  filter(year == 2018) %&gt;% 
  pull(size_mm)

# 2012 observations mpa vs non-mpa   
mn12_ttest &lt;- t.test(sample_mpa_12, sample_nmpa_12)
mn12_ttest # sig diff</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sample_mpa_12 and sample_nmpa_12
## t = -3.3723, df = 23.654, p-value = 0.002559
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -16.41918  -3.94582
## sample estimates:
## mean of x mean of y 
##   65.6875   75.8700</code></pre>
<p>When the lobster sizes observed in 2012 within the two MPA sites and within the three non-MPA sites are compared, it seems reasonable to conclude that there is a significant difference between the two. The actual difference between the two means is 10. A Welch Two Sample t-test with 23.65 degrees of freedom, and a t-statistic of -3.37 yeilded a p-value of 0.003 indicating that there is only a 0.3% chance that there is no difference between the observed sizes of lobsters within MPA sites and within non-MPA sites.</p>
<pre class="r"><code># 2018 observations mpa vs non-mpa
mn18_ttest &lt;- t.test(sample_mpa_18, sample_nmpa_18)
mn18_ttest # sig diff</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sample_mpa_18 and sample_nmpa_18
## t = 4.6828, df = 576.33, p-value = 3.532e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.250928 5.503165
## sample estimates:
## mean of x mean of y 
##  77.79133  73.91429</code></pre>
<p>Similar to that found in 2012, when the lobster sizes observed in 2018 within the two MPA sites and within the three non-MPA sites are compared, it seems reasonable to conclude that there is a significant difference between the two. The actual difference between the two means is 4. A Welch Two Sample t-test with 576.33 degrees of freedom, and a t-statistic of 4.68 yeilded a p-value of 0.000003 indicating that there is only a 0.0004% chance that there is no difference between the observed sizes of lobsters within MPA sites and within non-MPA sites.</p>
<pre class="r"><code># MPA sites only
mpa_ttest &lt;- t.test(sample_mpa_12, sample_mpa_18)
mpa_ttest # sig diff</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sample_mpa_12 and sample_mpa_18
## t = -4.4321, df = 15.993, p-value = 0.0004188
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -17.893355  -6.314309
## sample estimates:
## mean of x mean of y 
##  65.68750  77.79133</code></pre>
<p>When the lobster sizes observed in 2012 within the two MPA sites are compared to those observed in 2018, it seems reasonable to conclude that there is a significant difference between the two. The actual difference between the two means is 12. A Welch Two Sample t-test with 15.99 degrees of freedom, and a t-statistic of -4.43 yeilded a p-value of 410^{-4} indicating that there is only a 0.04% chance that there is no difference between the observed sizes of lobsters between years 2012 and 2018.</p>
<pre class="r"><code># Non MPA sites only
nmpa_ttest &lt;- t.test(sample_nmpa_12, sample_nmpa_18)
nmpa_ttest #not sig diff.</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sample_nmpa_12 and sample_nmpa_18
## t = 1.2772, df = 148.66, p-value = 0.2035
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.070034  4.981462
## sample estimates:
## mean of x mean of y 
##  75.87000  73.91429</code></pre>
<p>When the lobster sizes observed in 2012 within the three non-MPA sites are compared to those observed in 2018, it is not reasonable to conclude that there is a significant difference between the two. The actual difference between the two means is 2. A Welch Two Sample t-test with 148.66 degrees of freedom, and a t-statistic of 1.28 yeilded a p-value of 0.204 indicating that there is a 20% chance that there is no difference between the observed sizes of lobsters between years 2012 and 2018. Since this is quite a high percentage, it is quite possible that the observed differences between the two groups are merely due to chance.</p>
<pre class="r"><code># Means
mean_mpa_2012 &lt;- mn12_ttest$estimate[1] 
mean_nonmpa_2012 &lt;- mn12_ttest$estimate[2]
mean_mpa_2018 &lt;- mn18_ttest$estimate[1] 
mean_nonmpa_2018 &lt;- mn18_ttest$estimate[2] 
# Calculate Standard Deviations
sd_mpa_2012 &lt;- sd(sample_mpa_12[&quot;size&quot;], na.rm = TRUE) 
sd_nonmpa_2012 &lt;- sd(sample_nmpa_12[&quot;size&quot;], na.rm = TRUE)
sd_mpa_2018 &lt;- sd(sample_mpa_18[&quot;size&quot;], na.rm = TRUE)
sd_nonmpa_2018 &lt;- sd(sample_nmpa_18[&quot;size&quot;], na.rm = TRUE)
# Calculate Sample Sizes
n_mpa_2012 &lt;- sum(!is.na(sample_mpa_12[&quot;size&quot;]))
n_nonmpa_2012 &lt;- sum(!is.na(sample_nmpa_12[&quot;size&quot;]))
n_mpa_2018 &lt;- sum(!is.na(sample_mpa_18[&quot;size&quot;]))
n_nonmpa_2018 &lt;- sum(!is.na(sample_nmpa_18[&quot;size&quot;]))

# Wrangle data for statistics summary table
lobster_sum_tab &lt;- lob_size_yr %&gt;%
  dplyr::mutate(
    MPA_Status = dplyr::case_when(
      site %in% &quot;AQUE&quot; ~ &quot;Non-MPA&quot;,
      site %in% &quot;CARP&quot; ~ &quot;Non-MPA&quot;,
      site %in% &quot;IVEE&quot; ~ &quot;MPA&quot;,
      site %in% &quot;MOHK&quot; ~ &quot;Non-MPA&quot;,
      site %in% &quot;NAPL&quot; ~ &quot;MPA&quot;
      )
    ) %&gt;% 
group_by(MPA_Status, year) %&gt;%
summarize(mean = mean(size_mm),
          sd = sd(size_mm),
          sample_size = n())

lobster_sum_tab %&gt;%
kable(col.names = c(&quot;MPA Status&quot;,
                    &quot;Year&quot;,
                    &quot;Mean Lobster Size [mm]&quot;,
                    &quot;Standard Deviation&quot;,
                    &quot;Size of Sample (Lobster Counts)&quot;),
      caption = &quot;Table 1: Mean lobster size, standard deviation, and size of samples for MPA and non-MPA sites in 2012 and 2018.&quot;) %&gt;%
kable_styling(bootstrap_options = &quot;striped&quot;,
              full_width = F,
              position = &quot;left&quot;
              ) %&gt;%
add_header_above(c(&quot;LOBSTER SIZE METRICS&quot; = 5))</code></pre>
<table class="table table-striped" style="width: auto !important; ">
<caption>
<span id="tab:unnamed-chunk-8">Table 1: </span>Table 1: Mean lobster size, standard deviation, and size of samples for MPA and non-MPA sites in 2012 and 2018.
</caption>
<thead>
<tr>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="5">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
LOBSTER SIZE METRICS
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
MPA Status
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:right;">
Mean Lobster Size [mm]
</th>
<th style="text-align:right;">
Standard Deviation
</th>
<th style="text-align:right;">
Size of Sample (Lobster Counts)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
MPA
</td>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
65.68750
</td>
<td style="text-align:right;">
10.75000
</td>
<td style="text-align:right;">
16
</td>
</tr>
<tr>
<td style="text-align:left;">
MPA
</td>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
77.79133
</td>
<td style="text-align:right;">
12.10836
</td>
<td style="text-align:right;">
623
</td>
</tr>
<tr>
<td style="text-align:left;">
Non-MPA
</td>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
75.87000
</td>
<td style="text-align:right;">
13.76400
</td>
<td style="text-align:right;">
100
</td>
</tr>
<tr>
<td style="text-align:left;">
Non-MPA
</td>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
73.91429
</td>
<td style="text-align:right;">
11.22656
</td>
<td style="text-align:right;">
280
</td>
</tr>
</tbody>
</table>
</div>
<div id="summary" class="section level2">
<h2>Summary</h2>
<p>As noted earlier, MPA and non-MPA lobster sizes from 2012 were found to vary significantly from each other. MPA and non-MPA lobster sizes from 2018 were also found to vary signficantly. When lobster sizes in 2012 were compared to those in 2018 within the MPA sites, a significant difference was also found. Only a comparison of lobster sizes within the non-MPA sites between years 2012 and 2018 did not yeild a significant difference between the two groups. However, as seen in the table above, the sample size for the 2012 MPA lobsters was extremely small. Small sample sizes are more likely to inaacurately represent their true populations and thus, it is a bit risky to conclude there is a significant difference between the 2012 MPA and non-MPA lobsters. Ideally, more data would have been collected in 2012 to allow for a more robust comparison.
Generally, these findings seem to indicate that the positive impacts of MPAs start to manifest over time, since in 2018 more lobsters were found in the MPA sites and these lobsters tended to also be of larger body size. However, data should be examined for 2019 and 2020 in order to see if this trend continues.</p>
<div id="references" class="section level3">
<h3>References</h3>
<p>Data:
Reed D. 2019. SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012. Environmental Data Initiative. <a href="https://doi.org/10.6073/pasta/a593a675d644fdefb736750b291579a0" class="uri">https://doi.org/10.6073/pasta/a593a675d644fdefb736750b291579a0</a>. Dataset accessed 10/30/2019.</p>
</div>
</div>

    </div>

    





<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/timeseries/">timeseries</a>
  
  <a class="badge badge-light" href="/tags/statistical/">statistical</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/project/lobsters/kat_waldo_esm206_ass4_lobsters/&amp;text=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/project/lobsters/kat_waldo_esm206_ass4_lobsters/&amp;t=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER&amp;body=/project/lobsters/kat_waldo_esm206_ass4_lobsters/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/project/lobsters/kat_waldo_esm206_ass4_lobsters/&amp;title=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER%20/project/lobsters/kat_waldo_esm206_ass4_lobsters/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/project/lobsters/kat_waldo_esm206_ass4_lobsters/&amp;title=Spiny%20lobster%20abundance%20and%20size%20within%20Santa%20Barbara%20LTER" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
  





  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="avatar mr-3 avatar-circle" src="/authors/admin/avatar_huf5aa60df05f8c99cfcc01f68734e0eaa_4510707_270x270_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Oswaldo Felix</a></h5>
      <h6 class="card-subtitle">MESM Class of 2021</h6>
      <p class="card-text">My research interests include climate and energy, data science, and entrepreneurship.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/ozziedudias" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/oswaldof4" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>












  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/project/mono_lake/mono_lake/">Mono Lake Annual Levels</a></li>
      
    </ul>
  </div>
  



    <div class="project-related-pages content-widget-hr">
      
      

      
      
      

      
      
      

      
      
      
    </div>
  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.c816d323c3a55093dae0829b44ea1ca8.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
    
  </p>
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
